# Generated by Django 3.1.7 on 2021-04-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210405_0846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
