# Generated by Django 3.1.7 on 2021-04-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_intructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_more_information',
            name='Pincode',
        ),
        migrations.AddField(
            model_name='customer_more_information',
            name='Postcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
