# Generated by Django 3.1.7 on 2021-04-08 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('order', '0006_auto_20210407_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor_information'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 9, 8, 35, 863868)),
        ),
    ]
