# Generated by Django 3.1.7 on 2021-04-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210408_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 16, 38, 34, 18600)),
        ),
    ]
