# Generated by Django 3.1.7 on 2021-04-08 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210408_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancel_order',
            new_name='customer_cancel_order',
        ),
        migrations.AddField(
            model_name='order',
            name='instructor_cancel_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 17, 46, 9, 591286)),
        ),
    ]
