# Generated by Django 3.1.7 on 2021-04-09 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_intructor'),
        ('order', '0009_auto_20210408_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 9, 11, 28, 19, 117022)),
        ),
    ]
