# Generated by Django 3.1.7 on 2021-04-09 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210409_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_bill',
            new_name='Lesson_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 9, 15, 39, 0, 658441)),
        ),
    ]
