# Generated by Django 3.1.7 on 2021-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210410_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(max_length=1000),
        ),
    ]
